#默认配置
#server:
#  port: 8080
#  servlet:
#    context-path: /

#整合datasource
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: 123456

#默认配置
#mybatis:
#  configuration:
#    aggressive-lazy-loading: false
#    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    lazy-loading-enabled: true
mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml

net:
  litchi:
    showapi:
      appid: 899049
      appsecret: 887d838bfb0b45e99dfedd9ab6cd8d29
      covid: http://route.showapi.com/2217-2