#默认配置
#server:
#  port: 8080
#  servlet:
#    context-path: /

#整合datasource
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: 123456
  redis:
    database: 0
    password: 123456
    port: 6379
    host: 192.168.16.3
    timeout: 5000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=utf-8
  mvc:
    pathmatch:
      # 解决swagger和springboot2.6以上版本冲突
      matching-strategy: ant_path_matcher
  level:
    net.litchi: DEBUG
    org.springframework: INFO
#默认配置
#mybatis:
#  configuration:
#    aggressive-lazy-loading: false
#    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    lazy-loading-enabled: true

mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml

net:
  litchi:
    showapi:
      appid: 899049
      appsecret: 887d838bfb0b45e99dfedd9ab6cd8d29
      covid: http://route.showapi.com/2217-2